### ISSUE TITLE
Admin notice missing plugin name

### ISSUE THREAD

**Issue by nickcernis** [studiopress/genesis-simple-hooks#19]
Visible if 2.2.1 is active with a non-Genesis theme:

<img width="902" alt="plugins_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/49647294-4fd52180-fa22-11e8-964d-4eecf9cc48ab.png">

`$plugin['name']` needs to be `$plugin['Name']` here:

https://github.com/studiopress/genesis-simple-hooks/blob/0e7191eddd38e5e8a2dfb3af5f83a9c8b557782b/genesis-simple-hooks.php#L91

This isn't specific to WP 5.0, and it's correct in Simple FAQs here: 

https://github.com/studiopress/genesis-simple-faq/blob/21b2505dbfc264ea0fc7c5d63f7504da8bdf1bf4/genesis-simple-faq.php#L123

**Comment by nathanrice** [comment]
Fixed in 4659463
